### PR TITLE
Fix cast error from `AdsPixel` to `APINode` when submitting CAPI requests

### PR DESCRIPTION
**Pull request by pmscosta**
The SDK cannot be used to send CAPI requests due to a bug in the `sendEventToCAPIOnly()` method where it tries to cast an `APINode` type (returned by the `executeAsync()` method of a [`AdsPixel`](https://github.com/facebook/facebook-java-business-sdk/blob/main/src/main/java/com/facebook/ads/sdk/AdsPixel.java#L1918-L1920)) to an `AdsPixel`. 

Related issues: https://github.com/facebook/facebook-java-business-sdk/issues/408

Related commits: https://github.com/facebook/facebook-java-business-sdk/commit/97b153c3a0719026ed30e21d599b3966cac399d2  fixed this issue only for the `sendEventAsyncToCAPIAndCustomEndpoint` method.

These changes were tested in a dev environment, and I could successfully send the requests and see them on the Events Manager view of Facebook.

### CODE REVIEW

**Comment by judearavinda** [comment]
Can you put a more thorough test plan of sending requests in a before and after code change. Otherwise LGTM!

**Comment by pmscosta** [comment]
I've tried to create a unit test around the `sendEventToCAPIOnly` method of `EventRequest` class, however I couldn't get past this error when decoding the pixel response (`{"error":{"message":"Invalid OAuth access token - Cannot parse access token","type":"OAuthException","code":190,"fbtrace_id":"A4Sf-q3hDVN8pI4ktPegAvw"}}`).

Nonetheless, we can test the old and new behaviour with something like the following (notice we are _not_  setting the `endpointRequest` field of the EventRequest):
```java
    final String pixelId = "pixel-id-1";
    final APIContext mockApiContext = mock(APIContext.class);
    final EventRequest eventRequest = new EventRequest(pixelId, mockApiContext);
    final EventResponse reponse = eventRequest.executeAsync().get();
```

Before this change, this snippet would fail with something like:
```
Execution java.lang.ClassCastException: com.facebook.ads.sdk.APINode cannot be cast to com.facebook.ads.sdk.AdsPixel
```

After this code change, we are able to obtain a response.


If you can point me in the direction of providing a valid mock access token in the test I was trying to do, I'll gladly add it as well. Bellow follows my attempt at creating the spec: 

<details>

<summary> Click to open </summary>

```java 
  @Test
  public void sendAsyncToCAPIOnly() throws APIException, ExecutionException, InterruptedException {
    final String pixelId = "pixel-id-1";
    final APIContext mockApiContext = mock(APIContext.class);
    final EventRequest eventRequest = new EventRequest(pixelId, mockApiContext);
    final HttpServiceInterface mockClient = mock(HttpServiceInterface.class);
    final EventResponse mockEventResponse = mock(EventResponse.class);
    final String accessToken = "access-token-0";
    final String appSecretProof = "app-secret-proof-01";
    final String expectedUrl = String.format("%s/%s/%s/events",
        APIConfig.DEFAULT_API_BASE,
        APIConfig.DEFAULT_API_VERSION,
        pixelId
    );

    doReturn(accessToken).when(mockApiContext).getAccessToken();
    doReturn(expectedUrl).when(mockApiContext).getEndpointBase();
    doReturn(true).when(mockApiContext).hasAppSecret();
    doReturn(appSecretProof).when(mockApiContext).getAppSecretProof();
    doReturn(mockEventResponse).when(mockClient).executeRequest(
        ArgumentMatchers.<String>any(),
        ArgumentMatchers.<HttpMethodEnum>any(),
        ArgumentMatchers.<Map<String, String>>any(),
        ArgumentMatchers.<HttpServiceParams>any()
    );

    eventRequest.setHttpServiceClient(mockClient);
    final Event testEvent1 = new Event();
    testEvent1.setEventId("1");
    testEvent1.setEventName("testEvent1");
    eventRequest.addDataItem(testEvent1);

    // All the response fields are set to none due to an error with the access token
    // {"error":{"message":"Invalid OAuth access token - Cannot parse access token","type":"OAuthException","code":190,"fbtrace_id":"A4Sf-q3hDVN8pI4ktPegAvw"}}
    // This error can be seen by adding a `System.out.println(pixel.getRawResponse());` to the EventRequest.sendEventToCAPIOnly method
    final EventResponse reponse = eventRequest.executeAsync().get();
    assertEquals(response.getEventsReceived(), new Integer(1));
  }
```

</details>

**Comment by stcheng** [comment]
@pmscosta could you rename the variable name from pixel to node to match the type change?

**Comment by pmscosta** [comment]
> @pmscosta could you rename the variable name from pixel to node to match the type change?

Yes, done in https://github.com/facebook/facebook-java-business-sdk/pull/416/commits/6fc71c732334ced338086b4c69086cd596709f5f.

**Pull request closed without merging**
