### PR TITLE
fix: `ExtendedDeviceInfo` attributes addition

### PR DESCRIPTION
**Pull request by An1s9n**
Dear team, I kindly ask you to accept my pull request. It brings following benefits:

- while setting attributes you do not depend on attributes ordering anymore (before this fix if you would try to set attributes in arbitrary order you are likely to receive `IndexOutOfBoundsException`)
- you can safely omit attributes you can not provide (facebook api asks to send empty string `""` if you can not provide some attribute, but this SDK forces you to provide all attributes. Yes, you can pass `""` manually, but it would be nice if it would be a default behavior managed by SDK)
- make integer attributes safely nullable (in cases of `String` attributes you can pass manually `""`, but in case of `int` this is not possible. It would be nice if user of this SDK would pass just an `Integer` object not caring about possible nulls. Nulls will be translated to empty strings by SDK

### CODE REVIEW

**Comment by An1s9n** [comment]
Anyone?

**Comment by stcheng** [comment]
@An1s9n thank you for the PR. I'll try to review it and get back to you.

**Comment by An1s9n** [comment]
@stcheng, just let me know if there is something I can fix: I would be more than happy to do so :)

**Comment by An1s9n** [comment]
Any news about this..? Want to complete all TODOs in my project :)

**Comment by An1s9n** [comment]
@stcheng, thank you!)

**Pull request closed without merging**
